=== NCIP/geneconnect/Coding and Testing/GeneConnect/Config/CommandFile.dtd
<!ELEMENT CommandFile (DataSource+)>

<!ELEMENT DataSource (ExternalParser?,BaseDirectory+) >
<!ATTLIST DataSource
name CDATA #REQUIRED
type CDATA #REQUIRED
siteurl CDATA #REQUIRED
username CDATA #REQUIRED
password CDATA #REQUIRED
format CDATA #IMPLIED
proxyhost CDATA #IMPLIED
proxyport CDATA #IMPLIED
>
<!ELEMENT ExternalParser (Arg*)>
<!ATTLIST ExternalParser
writeToDB (true|false) #IMPLIED
commandfile CDATA #REQUIRED
>
<!ELEMENT Arg EMPTY>
<!ATTLIST Arg
name CDATA #REQUIRED
value CDATA #REQUIRED
>
<!ELEMENT BaseDirectory (File+) >
<!ATTLIST BaseDirectory
dir CDATA #REQUIRED
islocal (true|false) #IMPLIED
>
<!ELEMENT File EMPTY>
<!ATTLIST File
name CDATA #REQUIRED
>

=== NCIP/geneconnect/geneconnect/Coding and Testing/GeneConnect/Config/First_Run_CommandFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommandFile SYSTEM "CommandFile.dtd">
<CommandFile>
	<DataSource name="ENSEMBL" type="FTP" siteurl="ftp.ensembl.org" 
 		username="anonymous" password="phataka@pathbox.wustl.edu">
 		<ExternalParser writeToDB="false" commandfile="ParserScripts/Ensembl_Parser.sh"/>
 		<BaseDirectory dir="/pub/release-40/homo_sapiens_40_36b/data/mysql/homo_sapiens_core_40_36b/" islocal="false">
 			<File name="CHECKSUMS.gz" />
 			<File name="alt_allele.txt.table.gz" />
 			<File name="analysis.txt.table.gz" />
 			<File name="analysis_description.txt.table.gz" />
 			<File name="assembly.txt.table.gz" />
 			<File name="assembly_bak.txt.table.gz" />
 			<File name="assembly_exception.txt.table.gz" />
 			<File name="attrib_type.txt.table.gz" />
 			<File name="chr2contig.txt.table.gz" />
 			<File name="clone2contig.txt.table.gz" />
 			<File name="coord_system.txt.table.gz" />
 			<File name="coord_system_bak.txt.table.gz" />
 			<File name="density_feature.txt.table.gz" />
 			<File name="density_type.txt.table.gz" />
 			<File name="dna.txt.table.gz" />
 			<File name="dna_align_feature.txt.table.gz" />
 			<File name="dnac.txt.table.gz" />
 			<File name="exon.txt.table.gz" />
 			<File name="exon_stable_id.txt.table.gz" />
 			<File name="exon_transcript.txt.table.gz" />
 			<File name="external_db.txt.table.gz" />
 			<File name="external_synonym.txt.table.gz" />
 			<File name="gene.txt.table.gz" />
 			<File name="gene_archive.txt.table.gz" />
 			<File name="gene_attrib.txt.table.gz" />
 			<File name="gene_stable_id.txt.table.gz" />
 			<File name="go_xref.txt.table.gz" />
 			<File name="homo_sapiens_core_39_36a.mysql40_compatible.sql.gz" />
 			<File name="homo_sapiens_core_39_36a.sql.gz" />
 			<File name="identity_xref.txt.table.gz" />
 			<File name="interpro.txt.table.gz" />
 			<File name="karyotype.txt.table.gz" />
 			<File name="map.txt.table.gz" />
 			<File name="mapping_session.txt.table.gz" />
 			<File name="marker.txt.table.gz" />
 			<File name="marker_feature.txt.table.gz" />
 			<File name="marker_map_location.txt.table.gz" />
 			<File name="marker_synonym.txt.table.gz" />
 			<File name="meta.txt.table.gz" />
 			<File name="meta_bak.txt.table.gz" />
 			<File name="meta_coord.txt.table.gz" />
 			<File name="misc_attrib.txt.table.gz" />
 			<File name="misc_feature.txt.table.gz" />
 			<File name="misc_feature_misc_set.txt.table.gz" />
 			<File name="misc_set.txt.table.gz" />
 			<File name="object_xref.txt.table.gz" />
 			<File name="oligo_array.txt.table.gz" />
 			<File name="oligo_feature.txt.table.gz" />
 			<File name="oligo_feature_backup.txt.table.gz" />
 			<File name="oligo_probe.txt.table.gz" />
 			<File name="peptide_archive.txt.table.gz" />
 			<File name="prediction_exon.txt.table.gz" />
 			<File name="prediction_transcript.txt.table.gz" />
 			<File name="protein_align_feature.txt.table.gz" />
 			<File name="protein_feature.txt.table.gz" />
 			<File name="qtl.txt.table.gz" />
 			<File name="qtl_feature.txt.table.gz" />
 			<File name="qtl_synonym.txt.table.gz" />
 			<File name="regulatory_factor.txt.table.gz" />
 			<File name="regulatory_factor_coding.txt.table.gz" />
 			<File name="regulatory_feature.txt.table.gz" />
 			<File name="regulatory_feature_object.txt.table.gz" />
 			<File name="regulatory_search_region.txt.table.gz" />
 			<File name="repeat_consensus.txt.table.gz" />
 			<File name="repeat_feature.txt.table.gz" />
 			<File name="sc2contig.txt.table.gz" />
 			<File name="seq_region.txt.table.gz" />
 			<File name="seq_region_attrib.txt.table.gz" />
 			<File name="seq_region_bak.txt.table.gz" />
 			<File name="simple_feature.txt.table.gz" />
 			<File name="stable_id_event.txt.table.gz" />
 			<File name="supporting_feature.txt.table.gz" />
 			<File name="transcript.txt.table.gz" />
 			<File name="transcript_attrib.txt.table.gz" />
 			<File name="transcript_stable_id.txt.table.gz" />
 			<File name="transcript_supporting_feature.txt.table.gz" />
 			<File name="translation.txt.table.gz" />
 			<File name="translation_attrib.txt.table.gz" />
 			<File name="translation_stable_id.txt.table.gz" />
 			<File name="unmapped_object.txt.table.gz" />
 			<File name="unmapped_reason.txt.table.gz" />
 			<File name="xref.txt.table.gz" />
 		</BaseDirectory>		
 	</DataSource>
	<DataSource name="ENTREZGENE" type="FTP" siteurl="ftp.ncbi.nih.gov" 
 		username="anonymous" password="phataka@pathbox.wustl.edu">
 		<BaseDirectory dir="/gene/DATA/ASN_BINARY/Mammalia/" islocal="false">
 			<File name="Homo_sapiens.ags.gz"/>
 		</BaseDirectory>		
 	</DataSource>
	<DataSource name="UNIGENE" type="FTP" siteurl="ftp.ncbi.nih.gov" 
 		username="anonymous" password="phataka@pathbox.wustl.edu">
 		<ExternalParser writeToDB="false" commandfile="ParserScripts/UnigeneParser.sh"/>
	 	<BaseDirectory dir="/repository/UniGene/Homo_sapiens/" islocal="false">
 			<File name="Hs.data.gz"/>
 		</BaseDirectory>		
 	</DataSource>
 	<DataSource name="ENTREZ_TO_REFSEQ" type="FTP" siteurl="ftp.ncbi.nih.gov" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/Entrez_Refseq.sh"/>
		<BaseDirectory dir="/gene/DATA/" islocal="false">
	 		<File name="gene2refseq.gz"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="UNIPROT_GENEBANK" type="HTTP" siteurl="http://pir.georgetown.edu/GeneConnect/uniprotkb2genebank.gz" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu" proxyhost="ptproxy.persistent.co.in" proxyport="8080">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/Uniprot_Genbank.sh"/>
		<BaseDirectory dir="/GeneConnect/" islocal="false">
	 		<File name="uniprotkb2genebank.gz"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="UNIPROT_REFSEQ" type="HTTP" siteurl="http://pir.georgetown.edu/GeneConnect/uniprotkb2refseq.gz" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu" proxyhost="ptproxy.persistent.co.in" proxyport="8080">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/Uniprot_Refseq.sh"/>
		<BaseDirectory dir="/GeneConnect/" islocal="false">
	 		<File name="uniprotkb2refseq.gz"/>
	 	</BaseDirectory>		
 	</DataSource>
</CommandFile>

=== NCIP/geneconnect/geneconnect/Coding and Testing/GeneConnect/Config/Second_Run_CommandFile.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
  Copyright Washington University at St. Louis

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/geneconnect/LICENSE.txt for details.
L-->

<!DOCTYPE CommandFile SYSTEM "CommandFile.dtd">
<CommandFile>
	<DataSource name="UNIPROT_DESTINATION_FASTA" type="FTP" siteurl="ftp.uniprot.org" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/FormatdbUniprot.sh"/>
	<BaseDirectory dir="/pub/databases/uniprot/current_release/knowledgebase/complete/" islocal="false">
	 		<File name="uniprot_sprot.fasta.gz"/>
			<File name="uniprot_trembl.fasta.gz"/>
	 	</BaseDirectory>		
 	</DataSource-->
 	<DataSource name="REFSEQPROTEIN" type="FTP" siteurl="ftp.ncbi.nih.gov" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/FormatdbRefSeqProt.sh"/>
		<BaseDirectory dir="/refseq/H_sapiens/mRNA_Prot/" islocal="false">
	 		<File name="human.protein.faa.gz"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="REFSEQMRNA" type="FTP" siteurl="ftp.ncbi.nih.gov" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/FormatdbRefSeqmRNA.sh"/>
		<BaseDirectory dir="/refseq/H_sapiens/mRNA_Prot/" islocal="false">
	 		<File name="human.rna.fna.gz"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="ENSEMBLTRANSCRIPT" type="FTP" siteurl="ftp.ensembl.org" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/FormatdbEnsemblTrans.sh"/>
		<BaseDirectory dir="/pub/current_homo_sapiens/data/fasta/cdna/
" islocal="false">
	 		<File name="Homo_sapiens.NCBI36.40.cdna.all.fa.gz"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="ENSEMBLPROTEIN" type="FTP" siteurl="ftp.ensembl.org" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/FormatdbEnsemblProt.sh"/>
		<BaseDirectory dir="/pub/current_homo_sapiens/data/fasta/pep/" islocal="false">
	 		<File name="Homo_sapiens.NCBI36.40.pep.all.fa.gz"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="GENEBANK PROTEIN" type="" siteurl="D:" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/GenbankProteinParser.bat"/>
		<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
	 		<File name="gbankproteinTestfile.dat"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="GENEBANK MRNA" type="" siteurl="D:" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/GenbankmRNAParser.bat"/>
		<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
	 		<File name="gbankmrnaTestFile.dat"/>
	 	</BaseDirectory>		
 	</DataSource>
</CommandFile>

=== NCIP/geneconnect/geneconnect/Coding and Testing/GeneConnect/Config/Third_Run_CommandFile.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
  Copyright Washington University at St. Louis

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/geneconnect/LICENSE.txt for details.
L-->

<!DOCTYPE CommandFile SYSTEM "CommandFile.dtd">
<CommandFile>

	<DataSource name="REFSEQ_MRNA" type="HTTP" siteurl="" 
	 	username="" password="" proxyhost="" proxyport="">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/RefSeqmRNA-XML_RPC_Client.sh"/>
		<BaseDirectory dir="/GeneConnect/" islocal="true">
	 		<File name="human.rna.fna"/>
	 	</BaseDirectory>		
 	</DataSource>

	<DataSource name="REFSEQ_PROTEIN" type="HTTP" siteurl="" 
	 	username="" password="" proxyhost="" proxyport="">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/RefSeqProtein-XML_RPC_Client.sh"/>
		<BaseDirectory dir="/GeneConnect/" islocal="true">
	 		<File name="human.protein.faa"/>
	 	</BaseDirectory>		
 	</DataSource>

	<DataSource name="UNIPROT" type="HTTP" siteurl="" 
	 	username="" password="" proxyhost="" proxyport="">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/UniProtKB-XML_RPC_Client.sh"/>
		<BaseDirectory dir="/GeneConnect/" islocal="true">
	 		<File name="uniprot_HUMAN.fasta"/>
	 	</BaseDirectory>		
 	</DataSource>

	<DataSource name="GENEBANK PROTEIN" type="" siteurl="" 
	 	username="" password="">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/GenBankProtein-XML_RPC_Client.sh"/>
		<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
	 		<File name="genbank_protein_Homo_sapiens.fasta"/>
	 	</BaseDirectory>		
 	</DataSource>
	
	<DataSource name="GENEBANK MRNA" type="" siteurl="" 
	 	username="" password="">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts/GenBankmRNA-XML_RPC_Client.sh"/>
		<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
			<File name="genbank_mRNA_Homo_sapiens.fasta"/>
	 	</BaseDirectory>		
 	</DataSource> 
</CommandFile>

=== NCIP/geneconnect/geneconnect/Coding and Testing/GeneConnect/Config/CommandFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommandFile SYSTEM "CommandFile.dtd">
<CommandFile>
	<!--DataSource name="ENTREZGENE" type="" siteurl="D:" 
 		username="anonymous" password="phataka@pathbox.wustl.edu">
 			<BaseDirectory dir="\Projects\EclipseWD\UniGeneParser" islocal="false">
 			<File name="Homo_sapiens.ags.gz"/>
 		</BaseDirectory>		
 	</DataSource-->
	<DataSource name="UNIGENE" type="" siteurl="D:" 
 		username="anonymous" password="phataka@pathbox.wustl.edu">
 		<ExternalParser writeToDB="false" commandfile="ParserScripts\unigeneparser.bat"/>
	 	<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
 			<File name="Hs.data.gz"/>
 		</BaseDirectory>		
 	</DataSource>
 	<DataSource name="REFSEQ" type="" siteurl="D:" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts\entreztorefseq.bat"/>
		<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
	 		<File name="gene2refseq.txt"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="UNIPROT_GENEBANK" type="" siteurl="D:" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts\uniprot2genbank.bat"/>
		<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
	 		<File name="uniprotkb2genebank.txt"/>
	 	</BaseDirectory>		
 	</DataSource>
	<DataSource name="UNIPROT_REFSEQ" type="" siteurl="D:" 
	 	username="anonymous" password="phataka@pathbox.wustl.edu">
	 	<ExternalParser writeToDB="false" commandfile="ParserScripts\uniprot2refseq.bat"/>
		<BaseDirectory dir="\WashU\code\UniGeneParser" islocal="true">
	 		<File name="uniprotkb2refseq.txt"/>
	 	</BaseDirectory>		
 	</DataSource>
</CommandFile>
